server:
  port: 9001
spring:
  application:
    name: hsms-9001
  main:
    allow-bean-definition-overriding: true
  datasource:
      password: ${renjia.password}
      username: ${renjia.username}
      url: ${renjia.url}
      driver-class-name: ${renjia.driver}
      type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
